version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    network_mode: bridge
    restart: unless-stopped
    privileged: true
    env_file: ./.env
    expose:
      - 6379
    ports:
      - $REDIS_PORT:$REDIS_PORT

  # api:
  #   container_name: api
  #   build: ./
  #   network_mode: bridge
  #   restart: unless-stopped
  #   command: 'npm run dev'
  #   depends_on:
  #     - mysqldb
  #     - redis
  #   ports:
  #     - $PORT:$PORT
  #   volumes:
  #     - /node_modules
  #   env_file: ./.env
  #   environment:
  #     REDIS_URL: "redis://redis_db:6379"
  #     NODE_ENV: $NODE_ENV
  #     PORT: $PORT
  #     DB_PORT: $DB_PORT
  #     WLIST: $WLIST
  #     DB_HOST: $DB_HOST
  #     DB_CONNECTION: $DB_CONNECTION
  #     DB_DATABASE: $DB_DATABASE
  #     DB_USERNAME: $DB_USERNAME
  #     DB_PASSWORD: $DB_PASSWORD
  #     JWT_SECRET: $JWT_SECRET
  #     SALT: $SALT
  #     ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
  #     CACHE_EXPIRATION_TIME: $CACHE_EXPIRATION_TIME
  #   links:
  #     - redis

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT