### create product
POST http://localhost:3001/api/v1/products/create
Content-Type: application/json

{
    "categoryId": 1,
    "productName": "addidas 011",
    "product_code": "P-5645623",
    "product_sku": "p-583423",
    "regular_price": 10,
    "sale_price": 32,
    "tags": "New, Sale, Featured",
    "sizes": "XS, XL, SM",
    "quantity": 1,
    "colors": "blue, black",
    "gender": "MALE",
    "isFeatured": true,
    "status": "Sale",
    "description": "Sneaker",
    "productImages": [
        "https://images.pexels.com/photos/5525050/pexels-photo-5525050.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load"
    ]
}
    
### update product
PATCH  http://localhost:3001/api/v1/products/update/1
Content-Type: application/json

{
    "categoryId": 1,
    "productName": "updated nike 321",
    "product_code": "P=2d223423434",
    "product_sku": "few2ccvvg34232344",
    "regular_price": 10,
    "sale_price": 19,
    "tags": "New, Sale, Featured",
    "sizes": "XS, XL, SM",
    "quantity": 1,
    "color": "blue, black",
    "gender": "MALE",
    "isFeatured": true,
    "status": true,
    "description": "Sneaker",
    "productImages": [
        "https://images.pexels.com/photos/14854394/pexels-photo-14854394.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load"
    ]
}


### update product 
PATCH http://localhost:3001/api/v1/products/update_is_featured/1
Content-Type: application/json

{
    "isFeatured": false
}

### delete product
DELETE http://localhost:3001/api/v1/products/delete/2

### by id
GET http://localhost:3001/api/v1/products/by_id/1

### by productName
GET http://localhost:3001/api/v1/products/by_productName?productName=sne&page=0&pageSize=10

### list
GET http://localhost:3001/api/v1/products/list


### list with pagination
GET http://localhost:3001/api/v1/products/list?page=0&pageSize=10