### create user
POST http://localhost:3001/api/v1/users/create
Content-Type: application/json

{
    "fullName": "Customer 1",
    "email": "cus@gmail.com",
    "password": "cus123!@#",
    "phone": "0934234234",
    "gender": "Female",
    "role": "Customer"
}   

### update user
PATCH http://localhost:3001/api/v1/users/update/14
Content-Type: application/json

{
    "fullName": "updated test",
    "email": "updatedtest9@gmail.com",
    "password": "admin123!@#",
    "img": "https://images.pexels.com/photos/14487514/pexels-photo-14487514.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load",
    "phone": "0934234234",
    "gender": "Female",
    "role": "Editor"
}

### list
GET http://localhost:3001/api/v1/users/list

### toggle status
POST http://localhost:3001/api/v1/users/toggle_status/14
Content-Type: application/json

{
    "status": true
}