### create category
POST http://localhost:3001/api/v1/categories/create
Content-Type: application/json

{
    "categoryName": "Grove Clone 9",
    "parentCategoryId": 7,
    "description": "Boxing",
    "img": "https://images.pexels.com/photos/15465414/pexels-photo-15465414.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load"
}

### update category
PATCH http://localhost:3001/api/v1/categories/update/16
Content-Type: application/json

{
    "categoryName": "updated Grove clone 9",
    "parentCategoryId": 3,
    "description": "Mobiles",
    "img": "https://res.cloudinary.com/techgater/image/upload/v1669198823/my-uploads/ixx3ym9ezdrizeaxepqg.webp"
}   

### delete category     
DELETE http://localhost:3001/api/v1/categories/delete/16


### list
GET http://localhost:3001/api/v1/categories/list


### parent category list    
GET http://localhost:3001/api/v1/categories/parent_category_list