### subscribe
POST http://localhost:3001/api/v1/subscribers/subscribe
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY3NDk4ODgyMSwiZXhwIjoxNjc1MDEwNDIxfQ.VW_UnGgzlC_cPBSn1OwhJcFTs37GsrhXvDKT7NR6L1o
Content-Type: application/json

{
    "email": "adminuser@gmail.com"
}

### unsubscribe
POST http://localhost:3001/api/v1/subscribers/unsubscribe/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY3NDk4ODgyMSwiZXhwIjoxNjc1MDEwNDIxfQ.VW_UnGgzlC_cPBSn1OwhJcFTs37GsrhXvDKT7NR6L1o


### list
GET http://localhost:3001/api/v1/subscribers/list?page=0&pageSize=10